# LuckPerms Configuration

# The name of the server, used for server specific permissions. Set to 'global' to disable.
server: global

# The default group assigned to all users on their first join.
default-group: default

# If users on this server should have their global permissions/groups applied.
include-global: true

# Which storage method the plugin should use.
# Currently supported: mysql, sqlite, flatfile
# Fill out connection info below if you're using MySQL
storage-method: sqlite

sql:
  address: localhost:3306
  database: minecraft
  username: root
  password: ''
  sync-minutes: 3