name: LuckPerms
author: Luck
version: 1.2
main: me.lucko.luckperms.LPBukkitPlugin
softdepend: [Vault]
description: A permissions plugin
commands:
  luckperms:
    description: Manage permissions
    aliases: [perms, permissions, lp, p, perm]