name: LuckPerms
version: ${release.version}.${git.closest.tag.commit.count}
description: A permissions plugin
author: Luck
website: https://github.com/lucko/LuckPerms

main: me.lucko.luckperms.bukkit.LPBukkitPlugin
load: STARTUP
softdepend: [PermissionsEx, GroupManager, PowerfulPerms, zPermissions, bPermissions] # For migration

commands:
  luckperms:
    description: Manage permissions
    aliases: [perms, permissions, lp, p, perm]


# Permissions are registered programmatically instead of here.