name: LuckPerms
author: Luck
version: ${project.version}.${git.closest.tag.commit.count}
main: me.lucko.luckperms.LPBukkitPlugin
softdepend: [Vault]
description: A permissions plugin
commands:
  luckperms:
    description: Manage permissions
    aliases: [perms, permissions, lp, p, perm]