# LuckPerms Configuration

# The name of the server, used for server specific permissions. Set to 'global' to disable.
server: bungee

# The default group assigned to all user on join.
default-group: default

# If users on this server should have their global permissions/groups applied.
include-global: false

# Which storage method the plugin should use.
# Currently supported: mysql & flatfile
# Fill out connection info below if you're using MySQL
storage-method: flatfile

sql:
  address: localhost:3306
  database: minecraft
  username: root
  password: ''
  sync-minutes: 3