# LuckPerms Configuration

# The name of the server, used for server specific permissions. Set to 'global' to disable.
server: bungee

# The default group assigned to all users on their first join.
default-group: default

# If users on this server should have their global permissions/groups applied.
include-global: false

# If this server is in offline or online mode.
# This setting allows a player to have the same UUID across a network of offline mode/mixed servers.

# You should generally reflect the setting in server.properties here. Except when...

# 1. You have Spigot servers connected to a BungeeCord proxy, with online-mode set to false, but 'bungeecord' set to true in the spigot.yml
#    AND 'ip-forward' set to true in the BungeeCord config.yml
#    In this case, set online-mode in LuckPerms to true, despite the server being in offline mode.

# 2. You are only running one server instance using LuckPerms, (not a network)
#    In this case, set online-mode to true no matter what is set in server.properties. (we can just fallback to the servers uuid cache)
online-mode: true

# If the plugin should apply wildcard permissions.
# If set to true, LuckPerms will detect wildcard permissions, and resolve & apply all registered permissions matching
# the wildcard. This will only work for plugins that define all of their permissions to the server.
apply-wildcards: true

# If the plugin should parse regex permissions.
# If set to true, LuckPerms will detect regex permissions, marked with "r=" at the start of the node, and resolve &
# apply all registered permissions matching the regex. This will only work for plugins that define all of their
# permissions to the server.
apply-regex: true

# If the plugin should complete and apply shorthand permissions.
# If set to true, LuckPerms will detect and expand shorthand node patterns.
apply-shorthand: true

# Which storage method the plugin should use.
# Currently supported: mysql & flatfile
# Fill out connection info below if you're using MySQL
storage-method: flatfile

sql:
  address: localhost:3306
  database: minecraft
  username: root
  password: ''
  sync-minutes: 3